### ISSUE TITLE
cameraCanceled never triggered

### ISSUE THREAD

**Issue by mrblog** [remirobert/RRCamera#1]
The cameraCanceled delegate method is never triggered because there is a bug at line 98 in RRCamera.m which is:

  if ([self.delegate respondsToSelector:@selector(cancelCamera)]) {

And to match the protocol specification it should be:

```
if ([self.delegate respondsToSelector:@selector(cameraCanceled)]) {
```

**Comment by remirobert** [comment]
thanks a lot for your report, i fixed the bug.
